name: t2itest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - numpy=1.24
  - pillow
  - opencv
  - pyyaml
  - tqdm
  - pip
  - pip:
      - torch==2.4.1
      - torchvision==0.19.1
      - torchaudio==2.4.1
      - transformers==4.27.4
      - pytorch-lightning==1.4.2
      - albumentations==0.4.3
      - einops==0.3.0
      - kornia==0.6.5
      - omegaconf==2.3.0
      - scikit-image
      - scipy==1.10.1
      - huggingface-hub
      - tensorboard
      - imageio
      - imageio-ffmpeg==0.4.2
      - imgaug==0.2.6
      - h5py
      - requests
      - ftfy
      - regex
      - tokenizers==0.13.3
      - torchmetrics==0.6.0
      - safetensors